manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/Whaleman1234
+    - name: nguyendown
+      url-base: https://github.com/nguyendown
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
+    - name: zmk-behavior-socd
+      remote: nguyendown
+      revision: main
  self:
    path: config
